# ── SSM Parameter for Join Token ──────────────────────────────────────────────
resource "aws_ssm_parameter" "cluster_join_token" {
  name        = "/${var.env}/k8s/join_token"
  description = "Token dynamically generated by Master for Worker nodes to join cluster"
  type        = "SecureString"
  value       = "placeholder-awaiting-master-initialization"

  lifecycle {
    ignore_changes = [value]
  }
}

# ── Security group: Master ─────────────────────────────────────────────────────
resource "aws_security_group" "master" {
  name        = "${var.env}-k8s-master-sg"
  description = "K8s master node"
  vpc_id      = var.vpc_id

  # Bare group - all rules are managed as separate aws_vpc_security_group_
  # {ingress,egress}_rule resources below, deliberately kept out of this
  # resource's own inline blocks. AWS Cloud Controller Manager also calls
  # AuthorizeSecurityGroupIngress/RevokeSecurityGroupIngress directly against
  # this same group at runtime (for LoadBalancer-type Services), outside
  # Terraform's control. Without ignore_changes here, the next `apply` would
  # see that externally-added rule as drift on this resource's computed
  # ingress/egress attributes and try to revert it - even though the group
  # was declared bare. This ignore_changes is what lets CCM and Terraform
  # coexist on the same security group.
  lifecycle {
    ignore_changes = [ingress, egress]
  }

  tags = {
    Name               = "${var.env}-k8s-master-sg"
    "cilium.io/pod-sg" = "true"
  }
}

# ── Security group: Worker ─────────────────────────────────────────────────────
resource "aws_security_group" "worker" {
  name        = "${var.env}-k8s-worker-sg"
  description = "K8s worker nodes"
  vpc_id      = var.vpc_id

  # See the comment on aws_security_group.master above - same rationale.
  lifecycle {
    ignore_changes = [ingress, egress]
  }

  tags = {
    Name                                        = "${var.env}-k8s-worker-sg"
    "kubernetes.io/cluster/${var.cluster_name}" = "owned"
    "cilium.io/pod-sg"                          = "true"
  }
}

# ── Master rules ───────────────────────────────────────────────────────────────
resource "aws_vpc_security_group_ingress_rule" "master_ingress_from_worker" {
  description                  = "All traffic from workers"
  security_group_id            = aws_security_group.master.id
  referenced_security_group_id = aws_security_group.worker.id
  ip_protocol                  = "-1"

  tags = { Name = "${var.env}-master-ingress-from-worker" }
}

resource "aws_vpc_security_group_ingress_rule" "master_ingress_self" {
  description                  = "All traffic from other masters (self)"
  security_group_id            = aws_security_group.master.id
  referenced_security_group_id = aws_security_group.master.id
  ip_protocol                  = "-1"

  tags = { Name = "${var.env}-master-ingress-self" }
}

resource "aws_vpc_security_group_ingress_rule" "master_ingress_ssh" {
  description       = "SSH fallback access, VPC-only - SSM Session Manager is the primary access path"
  security_group_id = aws_security_group.master.id
  cidr_ipv4         = var.vpc_cidr
  from_port         = 22
  to_port           = 22
  ip_protocol       = "tcp"

  tags = { Name = "${var.env}-master-ingress-ssh" }
}

# One rule per trusted CIDR (e.g. hub VPC via Transit Gateway) - the split
# resource type only accepts a single cidr_ipv4 per rule, unlike the old
# aws_security_group_rule's cidr_blocks list, so this is for_each'd instead
# of the previous count-based single rule.
resource "aws_vpc_security_group_ingress_rule" "master_ingress_api_from_trusted_cidrs" {
  for_each = toset(var.trusted_api_cidr_blocks)

  description       = "kube-apiserver from trusted CIDR (e.g. hub VPC via Transit Gateway)"
  security_group_id = aws_security_group.master.id
  cidr_ipv4         = each.value
  from_port         = 6443
  to_port           = 6443
  ip_protocol       = "tcp"

  tags = { Name = "${var.env}-master-ingress-api-${replace(each.value, "/", "-")}" }
}

resource "aws_vpc_security_group_egress_rule" "master_egress_all" {
  description       = "All outbound"
  security_group_id = aws_security_group.master.id
  cidr_ipv4         = "0.0.0.0/0"
  ip_protocol       = "-1"

  tags = { Name = "${var.env}-master-egress-all" }
}

# ── Worker rules ───────────────────────────────────────────────────────────────
resource "aws_vpc_security_group_ingress_rule" "worker_ingress_from_master" {
  description                  = "All traffic from master"
  security_group_id            = aws_security_group.worker.id
  referenced_security_group_id = aws_security_group.master.id
  ip_protocol                  = "-1"

  tags = { Name = "${var.env}-worker-ingress-from-master" }
}

resource "aws_vpc_security_group_ingress_rule" "worker_ingress_self" {
  description                  = "All traffic between workers (self)"
  security_group_id            = aws_security_group.worker.id
  referenced_security_group_id = aws_security_group.worker.id
  ip_protocol                  = "-1"

  tags = { Name = "${var.env}-worker-ingress-self" }
}

resource "aws_vpc_security_group_ingress_rule" "worker_ingress_ssh" {
  description       = "SSH from VPC"
  security_group_id = aws_security_group.worker.id
  cidr_ipv4         = var.vpc_cidr
  from_port         = 22
  to_port           = 22
  ip_protocol       = "tcp"

  tags = { Name = "${var.env}-worker-ingress-ssh" }
}

resource "aws_vpc_security_group_egress_rule" "worker_egress_all" {
  description       = "All outbound"
  security_group_id = aws_security_group.worker.id
  cidr_ipv4         = "0.0.0.0/0"
  ip_protocol       = "-1"

  tags = { Name = "${var.env}-worker-egress-all" }
}

# ── Cluster Mesh: pod-to-pod traffic from any other cluster in the fleet ─────
# Under ENI IPAM, pods carry real VPC IPs rather than a separate pod-CIDR.
# The SG must therefore admit traffic from the fleet's VPC-CIDR supernet,
# not from a synthetic pod-CIDR supernet.
resource "aws_vpc_security_group_ingress_rule" "worker_ingress_clustermesh_pods" {
  description       = "Cross-cluster pod traffic (Cilium Cluster Mesh, native routing) - pods now carry real VPC IPs under ENI mode"
  security_group_id = aws_security_group.worker.id
  cidr_ipv4         = var.vpc_cidr_supernet
  ip_protocol       = "-1"

  tags = { Name = "${var.env}-worker-ingress-clustermesh-pods" }
}

resource "aws_vpc_security_group_ingress_rule" "master_ingress_clustermesh_pods" {
  description       = "Cross-cluster pod traffic (Cilium Cluster Mesh, native routing), master runs pods too (not cordoned)"
  security_group_id = aws_security_group.master.id
  cidr_ipv4         = var.vpc_cidr_supernet
  ip_protocol       = "-1"

  tags = { Name = "${var.env}-master-ingress-clustermesh-pods" }
}

# ── Cluster Mesh: WireGuard-encapsulated pod traffic between clusters ────
# encryption.type=wireguard (master_init.sh.tpl) re-wraps ALL inter-node
# pod traffic as UDP/51871 between the nodes' real IPs (cilium_wg0) -
# see https://docs.cilium.io/en/stable/security/network/encryption-wireguard/.
# Intra-cluster this is already covered by the SG-reference rules below
# (worker_ingress_self, master_ingress_from_worker, etc - "-1" from a
# peer SG ID covers any protocol, including WireGuard). Cross-cluster
# there's no SG to reference, so it needs its own CIDR-scoped rule -
# clustermesh_pods (scoped to pod_cidr_supernet) never matches this
# traffic, because the wire-level source is the node's real IP, not the
# original pod IP.
locals {
  clustermesh_wireguard_sgs = {
    worker = aws_security_group.worker.id
    master = aws_security_group.master.id
  }
}

resource "aws_vpc_security_group_ingress_rule" "clustermesh_wireguard" {
  for_each          = local.clustermesh_wireguard_sgs
  description       = "Cilium WireGuard tunnel (cilium_wg0), fleet-wide - encrypts cross-cluster pod traffic"
  security_group_id = each.value
  cidr_ipv4         = var.vpc_cidr_supernet
  from_port         = 51871
  to_port           = 51871
  ip_protocol       = "udp"

  tags = { Name = "${var.env}-${each.key}-ingress-clustermesh-wireguard" }
}

# ── Cluster Mesh: clustermesh-apiserver NodePort from any other cluster ──────
# cilium-agent on a peer cluster connects with its node's real VPC IP
# (hostNetwork), not a pod IP - scoped to the VPC-CIDR supernet, not the
# pod-CIDR supernet above.
resource "aws_vpc_security_group_ingress_rule" "worker_ingress_clustermesh_apiserver" {
  description       = "clustermesh-apiserver NodePort, reachable from every cluster in the fleet"
  security_group_id = aws_security_group.worker.id
  cidr_ipv4         = var.vpc_cidr_supernet
  from_port         = var.clustermesh_nodeport
  to_port           = var.clustermesh_nodeport
  ip_protocol       = "tcp"

  tags = { Name = "${var.env}-worker-ingress-clustermesh-apiserver" }
}

# ── Cluster Mesh: clustermesh-apiserver NodePort, master side ────────────
# The cluster's mesh.cilium.io hostAlias points at the master's static
# private IP (master_private_ip), not a worker - so the master SG needs
# this ingress too, mirroring worker_ingress_clustermesh_apiserver above.
# Confirmed via `clustermesh-apiserver kvstoremesh-dbg troubleshoot`:
# TCP dial to <master_ip>:<clustermesh_nodeport> timed out (SG-blocked,
# not TLS/cert - those never got a chance to negotiate).
resource "aws_vpc_security_group_ingress_rule" "master_ingress_clustermesh_apiserver" {
  description       = "clustermesh-apiserver NodePort, reachable from every cluster in the fleet"
  security_group_id = aws_security_group.master.id
  cidr_ipv4         = var.vpc_cidr_supernet
  from_port         = var.clustermesh_nodeport
  to_port           = var.clustermesh_nodeport
  ip_protocol       = "tcp"

  tags = { Name = "${var.env}-master-ingress-clustermesh-apiserver" }
}

# ── IAM role: master ───────────────────────────────────────────────────────────
resource "aws_iam_role" "master" {
  name = "${var.env}-k8s-master-role"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect    = "Allow"
      Principal = { Service = "ec2.amazonaws.com" }
      Action    = "sts:AssumeRole"
    }]
  })

  tags = { Name = "${var.env}-k8s-master-role", Env = var.env }
}

resource "aws_iam_role_policy" "master_ssm_write" {
  name = "${var.env}-k8s-master-ssm-write-policy"
  role = aws_iam_role.master.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Sid      = "SSMWriteToken"
      Effect   = "Allow"
      Action   = ["ssm:PutParameter"]
      Resource = aws_ssm_parameter.cluster_join_token.arn
    }]
  })
}

# ── IRSA: master publishes its own OIDC discovery doc + JWKS ──────────────
# Scoped to this cluster's own prefix in the shared bucket only - the hub
# master can never write into a spoke's prefix or vice versa. See
# modules/k8s/templates/master_init.sh.tpl's publish step and
# modules/oidc-bucket/README.md for the full picture.
resource "aws_iam_role_policy" "master_oidc_publish" {
  count = var.oidc_bucket_arn != "" ? 1 : 0
  name  = "${var.env}-k8s-master-oidc-publish-policy"
  role  = aws_iam_role.master.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Sid      = "PublishOwnClusterOIDCDocsOnly"
      Effect   = "Allow"
      Action   = ["s3:PutObject"]
      Resource = "${var.oidc_bucket_arn}/${var.oidc_s3_prefix}/*"
    }]
  })
}

resource "aws_iam_instance_profile" "master" {
  name = "${var.env}-k8s-master-profile"
  role = aws_iam_role.master.name
}

# ── Master → SSM Session Manager ───────────────────────────────────────────
resource "aws_iam_role_policy_attachment" "master_ssm" {
  role       = aws_iam_role.master.name
  policy_arn = "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore"
}

# ── IAM role: worker (used by ASG launch template) ────────────────────────────
resource "aws_iam_role" "worker" {
  name = "${var.env}-k8s-worker-role"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect    = "Allow"
      Principal = { Service = "ec2.amazonaws.com" }
      Action    = "sts:AssumeRole"
    }]
  })

  tags = { Name = "${var.env}-k8s-worker-role", Env = var.env }
}

# ── Worker → SSM Session Manager ────────────────────────────────────────────
resource "aws_iam_role_policy_attachment" "worker_ssm" {
  role       = aws_iam_role.worker.name
  policy_arn = "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore"
}

resource "aws_iam_instance_profile" "worker" {
  name = "${var.env}-k8s-worker-profile"
  role = aws_iam_role.worker.name
}

# ── Master node ────────────────────────────────────────────────────────────────
resource "aws_instance" "master" {
  # AMI is the shared, Packer-built k8s base image (containerd/kubeadm/
  # kubelet/kubectl + node prep baked in) - see /packer and modules/ami.
  #
  # NOTE: no user_data here anymore. kubelet is enabled by the AMI but sits
  # idle (no /etc/kubernetes/kubelet.conf yet) until the k8s-cluster-bootstrap.yml
  # CI workflow runs kubeadm init via SSM send-command, using
  # module.k8s.master_userdata as the script content. This makes a failed
  # bootstrap fail a CI job with logs, instead of failing silently inside
  # cloud-init. See modules/k8s/README.md.
  #
  # Master lives in a private subnet, same as workers - no public IP.
  # Reached exclusively via SSM Session Manager (see the unconditional
  # aws_iam_role_policy_attachment.master_ssm above); SSH stays available
  # only as a VPC-internal fallback (see master_ingress_ssh above).
  ami                         = var.ami_id
  instance_type               = var.master_instance_type
  subnet_id                   = var.private_subnet_ids[0]
  private_ip                  = var.master_private_ip
  associate_public_ip_address = false
  vpc_security_group_ids      = [aws_security_group.master.id]
  key_name                    = var.key_name
  iam_instance_profile        = aws_iam_instance_profile.master.name

  # Required for Cilium native routing: AWS drops any packet whose source
  # IP doesn't match the ENI's own primary/secondary IP unless this check
  # is disabled. Pods running on the master (it's not cordoned) send
  # traffic with a pod-CIDR source IP, not the instance's ENI IP.
  source_dest_check = false

  root_block_device {
    volume_size = var.master_volume_size
    volume_type = "gp3"
  }

  tags = { Name = "${var.env}-k8s-master", Role = "master", Env = var.env, "kubernetes.io/cluster/${var.cluster_name}" = "owned" }
}

# ── Hub discover new spokes logic block  ────────────────────────────────────────────────────────────────
data "aws_caller_identity" "current" {}
data "aws_region" "current" {}

# ── Spoke → push its own Argo CD registration credentials to Secrets Manager ──
resource "aws_iam_role_policy" "master_argocd_registration_push" {
  count = var.register_with_hub ? 1 : 0
  name  = "${var.env}-k8s-master-argocd-registration-policy"
  role  = aws_iam_role.master.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Sid    = "PushOwnRegistrationSecretOnly"
      Effect = "Allow"
      Action = [
        "secretsmanager:CreateSecret",
        "secretsmanager:PutSecretValue",
        "secretsmanager:TagResource",
        "secretsmanager:DescribeSecret"
      ]
      Resource = "arn:aws:secretsmanager:${data.aws_region.current.name}:${data.aws_caller_identity.current.account_id}:secret:argocd-clusters/${var.cluster_name}-*"
    }]
  })
}
